name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (to run npm commands)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        uses: anothrNick/github-tag-action@v1.37.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          release_branches: main
          tag_name: "v${{ steps.get_version.outputs.version }}"
